NDefines.NSpecies.MAX_ETHIC_POINTS = 4
NDefines.NSpecies.MAX_TRAITS = 4
NDefines.NSpecies.MAX_TRAIT_POINTS = 3
NDefines.NSpecies.MAX_TRAIT_POINTS_LEADER = 2

NDefines.NGameplay.ETHOS_MAX_POINTS = 4
NDefines.NGameplay.ETHOS_DISTRIBUTION_FACTOR = 1.0
NDefines.NGameplay.CORE_SECTOR_SYSTEM_CAP = 3
NDefines.NGameplay.SECTOR_CAP = 5
NDefines.NGameplay.MAX_ANOMALIES = 3
NDefines.NGameplay.LEADER_POOL_LEAD_TIME = 3
NDefines.NGameplay.LEADER_BASE_CAP = 20
NDefines.NGameplay.LEADER_AGE_HEIR_MIN = 16
NDefines.NGameplay.LEADER_AGE_HEIR_MAX = 30
NDefines.NGameplay.LEADER_AGE_MIN = 18
NDefines.NGameplay.LEADER_AGE_MAX = 40
NDefines.NGameplay.LEADER_AGE_DEATH_CHANCE_AGE = 65
NDefines.NGameplay.LEADER_AGE_DEATH_CHANCE_INC = 0.005

NDefines.NAI.DISTANCE_STARS_RESEARCH = 20

NDefines.NGraphics.MAPNAME_NEBULA_SCALE = 0.9

NDefines.NGameplay.ADVANCED_EMPIRE_EXTRA_MINERALS_MAX = 1000
NDefines.NGameplay.ADVANCED_EMPIRE_EXTRA_ENERGY_MAX = 500
NDefines.NGameplay.ADVANCED_EMPIRE_EXTRA_INFLUENCE_MIN = 25 
NDefines.NGameplay.ADVANCED_EMPIRE_EXTRA_INFLUENCE_MAX = 75
NDefines.NGameplay.ADVANCED_EMPIRE_EXTRA_WARSHIPS_MAX = 5
NDefines.NGameplay.ADVANCED_EMPIRE_MAX_EXTRA_COLONIES = 2
NDefines.NGameplay.ADVANCED_EMPIRE_COLONY_POPS = 2
NDefines.NGameplay.ADVANCED_EMPIRE_COLONY_NUM_POWER_PLANTS = 1 

NDefines.NGameplay.HYPERLANE_GEN_REMOVE_PERC = 0.35
NDefines.NGameplay.HYPERLANE_GEN_REMOVE_TOO_MANY_EDGES = 3
